#!/usr/bin/bash

# Convert a torch-distributed-checkpoint to plain torch checkpoint
# This will generate a 'torch.pth' file inside the distributed checkpoint path
# IMPORTANT: Do not specify a *.distcp file, instead specify the root directory.
#
# Example: sh smiths/distcp2pth outputs/hif_dinov3/ckpt/999
#
# Author: Soumen Sardar
# Date: 2026-02-19





python -m torch.distributed.checkpoint.format_utils dcp_to_torch $1 $1/torch.pth